### ISSUE TITLE
Environment output in default image should be alphabetically sorted

### ISSUE THREAD

**Issue by mthaddon** [canonical/gunicorn-k8s-operator#9]
### Enhancement Proposal

Currently if you spin up the default image and connect to the charm in a browser you get a dump of the environment variables that have been passed in.

It would be more readable if these were sorted alphabetically in case the user is looking for a particular variable.

**Comment by gtrkiller** [comment]
Solved in https://github.com/canonical/gunicorn-k8s-operator/pull/25
